# Generated by Django 5.2 on 2025-08-14 10:01

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_pages", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpageentry",
            name="timestamp",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="landingpageentry",
            name="updated",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="landingpageentry",
            name="name",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
