# Generated by Django 5.2 on 2025-08-14 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "landing_pages",
            "0002_landingpageentry_timestamp_landingpageentry_updated_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpageentry",
            name="active",
            field=models.BooleanField(default=True),
        ),
    ]
