# Generated by Django 5.2 on 2025-08-15 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_pages", "0003_landingpageentry_active"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpageentry",
            name="notes",
            field=models.TextField(blank=True, null=True),
        ),
    ]
