# Generated by Django 5.2 on 2025-08-18 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("landing_pages", "0005_landingpageentry_notes_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="landingpageentry",
            name="note_first_addeed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
